# Generated by Django 5.2.17 on 2026-09-22 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='wasteevent',
            index=models.Index(fields=['user', 'occurred_on'], name='analytics_w_user_id_58c2de_idx'),
        ),
    ]
