# Generated by Django 5.2.17 on 2026-09-22 09:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=512)),
                ('found', models.BooleanField(default=False)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(default='item', max_length=24)),
                ('purchased_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(db_index=True)),
                ('opened_on', models.DateField(blank=True, null=True)),
                ('storage_location', models.CharField(choices=[('pantry', 'Pantry'), ('fridge', 'Fridge'), ('freezer', 'Freezer')], default='pantry', max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('discarded', 'Discarded')], db_index=True, default='active', max_length=12)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='products.product')),
            ],
            options={
                'ordering': ['expires_on'],
            },
        ),
    ]
