# Generated by Django 5.2.17 on 2026-09-22 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='products.product'),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['user', 'expires_on'], name='inventory_i_user_id_8f9e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['user', 'storage_location'], name='inventory_i_user_id_e56ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['user', 'status', 'expires_on'], name='inventory_i_user_id_07bb32_idx'),
        ),
        migrations.AddIndex(
            model_name='scanhistory',
            index=models.Index(fields=['user', 'scanned_at'], name='inventory_s_user_id_07f96e_idx'),
        ),
    ]
