import { createContext, useContext, useEffect, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { CheckCircle2, LoaderCircle, Mail } from 'lucide-react';
import { PublicNav } from './components/layout'; import { Button, Card } from './components/ui';

const API_URL = import.meta.env.VITE_API_URL ?? 'http://localhost:8000/api';
type User={id:number;email:string;first_name:string;last_name:string}; type AuthValue={user:User|null;login:(email:string,password:string,remember:boolean)=>Promise<void>;registerUser:(name:string,email:string,password:string)=>Promise<void>;logout:()=>Promise<void>};
const AuthContext=createContext<AuthValue|undefined>(undefined);
const store=(remember:boolean)=>remember?localStorage:sessionStorage;
const tokens=()=>({access:localStorage.getItem('fg_access')??sessionStorage.getItem('fg_access'),refresh:localStorage.getItem('fg_refresh')??sessionStorage.getItem('fg_refresh')});
const clearTokens=()=>{for(const s of [localStorage,sessionStorage]){s.removeItem('fg_access');s.removeItem('fg_refresh')}};
async function request(path:string, init:RequestInit={}, retry=true){const defaultHeaders: Record<string, string>=init.body instanceof FormData?{}:{'Content-Type':'application/json'};const res=await fetch(`${API_URL}${path}`,{...init,headers:{...defaultHeaders,...((init.headers as Record<string, string>)||{})}});if(res.status===401&&retry&&tokens().refresh){const refresh=await fetch(`${API_URL}/auth/token/refresh/`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh:tokens().refresh})});if(refresh.ok){const next=await refresh.json();const s=localStorage.getItem('fg_refresh')?localStorage:sessionStorage;s.setItem('fg_access',next.access);return request(path,init,false)}}const body=await res.json().catch(()=>({}));if(!res.ok) throw new Error(body.detail||Object.values(body).flat().join(' ')||'Something went wrong. Please try again.');return body}
export async function authenticatedRequest(path:string,init:RequestInit={}) { const access=tokens().access; if(!access) throw new Error('Your session has expired. Please sign in again.'); return request(path,{...init,headers:{Authorization:`Bearer ${access}`,...((init.headers as Record<string, string>)||{})}}) }
export function AuthProvider({children}:{children:React.ReactNode}){const [user,setUser]=useState<User|null>(null);useEffect(()=>{if(tokens().access) request('/auth/me/',{headers:{Authorization:`Bearer ${tokens().access}`}}).then(setUser).catch(clearTokens)},[]);const login=async(email:string,password:string,remember:boolean)=>{const data=await request('/auth/login/',{method:'POST',body:JSON.stringify({email,password})});const s=store(remember);clearTokens();s.setItem('fg_access',data.access);s.setItem('fg_refresh',data.refresh);setUser(data.user)};const registerUser=async(name:string,email:string,password:string)=>{const data=await request('/auth/register/',{method:'POST',body:JSON.stringify({first_name:name,email,password})});const s=localStorage;clearTokens();s.setItem('fg_access',data.access);s.setItem('fg_refresh',data.refresh);setUser(data.user)};const logout=async()=>{try{await request('/auth/logout/',{method:'POST',body:JSON.stringify({refresh:tokens().refresh}),headers:{Authorization:`Bearer ${tokens().access}`}})}finally{clearTokens();setUser(null)}};return <AuthContext.Provider value={{user,login,registerUser,logout}}>{children}</AuthContext.Provider>}
export const useAuth=()=>{const c=useContext(AuthContext);if(!c)throw new Error('useAuth must be used in AuthProvider');return c};
const Notice=({message,error}:{message:string;error?:boolean})=><div role="alert" className={'rounded-xl px-4 py-3 text-sm '+(error?'bg-red-50 text-red-700 dark:bg-red-950/30 dark:text-red-300':'bg-mint text-forest')}>{message}</div>;
export function AuthPage({register=false}:{register?:boolean}){const {login,registerUser}=useAuth();const nav=useNavigate();const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');setMessage('');setBusy(true);const form=new FormData(e.currentTarget);try{if(register){await registerUser(form.get('name')?.toString().trim()||'',String(form.get('email')),String(form.get('password')));nav('/dashboard')}else{await login(String(form.get('email')),String(form.get('password')),form.get('remember')==='on');nav('/dashboard')}}catch(e){setError(e instanceof Error?e.message:'Unable to continue.')}finally{setBusy(false)}}return <div className="shell"><PublicNav/><main className="mx-auto grid min-h-[calc(100vh-73px)] max-w-7xl items-center gap-10 px-5 py-12 lg:grid-cols-2"><div className="hidden rounded-3xl bg-forest p-10 text-white lg:block"><Mail className="text-lime" size={34}/><h1 className="mt-24 text-5xl font-bold leading-tight">Safer food starts<br/>at home.</h1><p className="mt-5 max-w-sm text-white/65">Simple safety intelligence for every shelf, fridge, and pantry.</p></div><Card className="mx-auto w-full max-w-md p-7 md:p-9"><p className="text-sm font-semibold text-forest dark:text-lime">WELCOME TO FOODGUARD</p><h1 className="mt-2 text-3xl font-bold">{register?'Create your account':'Welcome back'}</h1><form className="mt-7 space-y-4" onSubmit={submit}>{register&&<label className="block text-sm font-medium">Full name<input name="name" className="input mt-1.5" required autoComplete="name"/></label>}<label className="block text-sm font-medium">Email address<input name="email" className="input mt-1.5" type="email" required autoComplete="email"/></label><label className="block text-sm font-medium">Password<input name="password" className="input mt-1.5" type="password" required minLength={12} autoComplete={register?'new-password':'current-password'}/>{register&&<small className="mt-1 block opacity-55">12+ characters with upper/lowercase letters and a number.</small>}</label>{!register&&<><label className="flex items-center gap-2 text-sm"><input name="remember" type="checkbox"/> Remember me</label><Link className="block text-right text-xs font-semibold text-forest dark:text-lime" to="/forgot-password">Forgot password?</Link></>}{error&&<Notice message={error} error/>}{message&&<Notice message={message}/>}<Button className="w-full" type="submit" disabled={busy}>{busy&&<LoaderCircle className="animate-spin" size={16}/>}{register?'Create account & Start':'Sign in'}</Button></form><p className="mt-6 text-center text-sm opacity-65">{register?'Already have an account?':'New to FoodGuard?'} <Link className="font-bold text-forest dark:text-lime" to={register?'/login':'/register'}>{register?'Log in':'Create an account'}</Link></p></Card></main></div>}
export function ForgotPassword(){return <PasswordForm mode="request"/>} export function ResetPassword(){return <PasswordForm mode="reset"/>}
function PasswordForm({mode}:{mode:'request'|'reset'}){const [query]=useSearchParams();const [message,setMessage]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const f=new FormData(e.currentTarget);const path=mode==='request'?'/auth/password-reset/':'/auth/password-reset/confirm/';const body=mode==='request'?{email:f.get('email')}:{uid:query.get('uid'),token:query.get('token'),password:f.get('password')};const result=await request(path,{method:'POST',body:JSON.stringify(body)});setMessage(result.message)}catch(e){setError(e instanceof Error?e.message:'Unable to reset password.')}finally{setBusy(false)}}return <div className="shell"><PublicNav/><main className="mx-auto max-w-md px-5 py-20"><Card className="p-7"><h1 className="text-3xl font-bold">{mode==='request'?'Reset your password':'Choose a new password'}</h1><p className="mt-2 text-sm opacity-60">{mode==='request'?'We’ll send reset instructions if the account exists.':'Use a strong, unique password.'}</p><form className="mt-6 space-y-4" onSubmit={submit}><input className="input" name={mode==='request'?'email':'password'} type={mode==='request'?'email':'password'} required minLength={mode==='reset'?12:undefined} placeholder={mode==='request'?'you@example.com':'New password'}/>{message&&<Notice message={message}/>} {error&&<Notice message={error} error/>}<Button type="submit" className="w-full" disabled={busy}>{busy?'Please wait…':mode==='request'?'Send reset link':'Reset password'}</Button></form></Card></main></div>}
export function VerifyEmail(){const [q]=useSearchParams();const [message,setMessage]=useState('Verifying your email…');const [error,setError]=useState('');useEffect(()=>{request('/auth/verify-email/',{method:'POST',body:JSON.stringify({uid:q.get('uid'),token:q.get('token')})}).then(x=>setMessage(x.message)).catch(e=>setError(e.message))},[]);return <div className="shell"><PublicNav/><main className="mx-auto max-w-md px-5 py-20"><Card className="p-8 text-center"><CheckCircle2 className="mx-auto text-forest dark:text-lime" size={42}/><h1 className="mt-5 text-2xl font-bold">Email verification</h1><p className="mt-3 text-sm opacity-65">{error||message}</p>{!error&&message!=='Verifying your email…'&&<Link className="btn-primary mt-6" to="/login">Sign in</Link>}</Card></main></div>}
